FROM golang:1.26 AS build
WORKDIR /src
COPY go/go.mod go/go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY go ./
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    go test ./cmd/cuan-hosted && CGO_ENABLED=0 go build -trimpath -ldflags='-s -w' -o /cuan-search-console ./cmd/cuan-hosted
FROM gcr.io/distroless/static-debian13:nonroot
COPY --from=build /cuan-search-console /cuan-search-console
EXPOSE 8080
ENTRYPOINT ["/cuan-search-console"]
